export const ALL_MY_ORDERS_REQUEST = 'ALL_MY_ORDERS_REQUEST';
export const ALL_MY_ORDERS_SUCCESS = 'ALL_MY_ORDERS_SUCCESS';
export const ALL_MY_ORDERS_FAIL = 'ALL_MY_ORDERS_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
