export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';

export const ALL_COUNTRIES_REQUEST = 'ALL_COUNTRIES_REQUEST';
export const ALL_COUNTRIES_SUCCESS = 'ALL_COUNTRIES_SUCCESS';
export const ALL_COUNTRIES_FAIL = 'ALL_COUNTRIES_FAIL';

export const ALL_STATES_REQUEST = 'ALL_STATES_REQUEST';
export const ALL_STATES_SUCCESS = 'ALL_STATES_SUCCESS';
export const ALL_STATES_FAIL = 'ALL_STATES_FAIL';
